# Generated by Django 4.2.6 on 2023-10-30 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Muebles', '0002_categoria_imagen_mueble_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mueble',
            options={'verbose_name': 'Mueble', 'verbose_name_plural': 'Muebles'},
        ),
        migrations.AddField(
            model_name='mueble',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Muebles_Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Muebles.mueble')),
            ],
            options={
                'verbose_name': 'Mueble en Oferta',
                'verbose_name_plural': 'Muebles en Oferta',
            },
        ),
    ]
