# Generated by Django 4.2.6 on 2023-11-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Muebles', '0004_promocion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='precio_maximo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='precio_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
