# Generated by Django 4.2.6 on 2023-11-09 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Muebles', '0005_alter_categoria_precio_maximo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mueble',
            old_name='imagen',
            new_name='imagen_portada',
        ),
        migrations.AddField(
            model_name='mueble',
            name='imagen_extra',
            field=models.ImageField(blank=True, null=True, upload_to='categorias'),
        ),
        migrations.AddField(
            model_name='mueble',
            name='imagen_extra1',
            field=models.ImageField(blank=True, null=True, upload_to='categorias'),
        ),
        migrations.AddField(
            model_name='mueble',
            name='imagen_extra2',
            field=models.ImageField(blank=True, null=True, upload_to='categorias'),
        ),
    ]
