# Generated by Django 4.2.6 on 2023-11-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Muebles', '0006_rename_imagen_mueble_imagen_portada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mueble',
            name='imagen_extra3',
            field=models.ImageField(blank=True, null=True, upload_to='categorias'),
        ),
    ]
